# Generated by Django 3.0.7 on 2020-08-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar', models.CharField(blank=True, default='/static/images/avatar.png', max_length=50)),
                ('salt', models.CharField(blank=True, max_length=6)),
                ('sign', models.CharField(blank=True, default='这个人很懒，什么也没说！', max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('state', models.BooleanField(default=0)),
                ('manager', models.BooleanField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('create_user_id', models.IntegerField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('file_path', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('hash', models.CharField(max_length=255, unique=True)),
                ('pub_date', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
                ('operator', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='Account')),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('avatar', models.CharField(blank=True, max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='create user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(default=0)),
                ('msg', models.TextField()),
                ('status', models.BooleanField(default=1)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('urgent', models.BooleanField()),
                ('pub_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='发布者')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('status', models.BooleanField(default=1)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='部门')),
            ],
            options={
                'unique_together': {('group_name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('servername', models.CharField(max_length=30)),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=50)),
                ('skey', models.BooleanField(default=0)),
                ('status', models.BooleanField()),
                ('pub_date', models.DateTimeField()),
                ('deny_user', models.ManyToManyField(blank=True, to='app01.Account')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ServerGroup', verbose_name='分组id')),
            ],
            options={
                'unique_together': {('ip', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=0)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_message_user', to='app01.Account', verbose_name='发送者')),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Message', verbose_name='message')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='接受者')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('content', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Schedule', verbose_name='任务')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='接受者')),
            ],
        ),
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('local', models.CharField(max_length=255)),
                ('remote', models.CharField(max_length=255)),
                ('size', models.IntegerField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('fail_server', models.ManyToManyField(to='app01.Server')),
                ('ip', models.ManyToManyField(related_name='server', to='app01.Server')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='操作者')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('ip', models.ManyToManyField(to='app01.Server')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='操作者')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('read_count', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='作者')),
                ('tags', models.ManyToManyField(blank=True, to='app01.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='操作者')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='GroupAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.BooleanField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Group', verbose_name='group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='user')),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='FriendGroupFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='Account')),
                ('friend_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.FriendGroup', verbose_name='FriendGroup')),
            ],
            options={
                'unique_together': {('friend_group', 'friend')},
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=0)),
                ('status', models.BooleanField(default=0)),
                ('is_pro_del', models.BooleanField(default=0)),
                ('is_rec_del', models.BooleanField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_proposer', to='app01.Account', verbose_name='申请者')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='接受者')),
            ],
            options={
                'unique_together': {('proposer', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('public', models.BooleanField()),
                ('pub_date', models.DateTimeField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='操作者')),
                ('tags', models.ManyToManyField(blank=True, to='app01.Tag')),
            ],
            options={
                'unique_together': {('title', 'operator')},
            },
        ),
    ]
