# Generated by Django 3.0.7 on 2020-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='former',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
