# Generated by Django 3.0.7 on 2020-08-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_message_former'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='former',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
