# Generated by Django 3.0.7 on 2020-08-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200823_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.FriendGroup', verbose_name='分组'),
            preserve_default=False,
        ),
    ]
