# Generated by Django 3.0.7 on 2020-08-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_friend_friend_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='notice',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
