# Generated by Django 3.0.7 on 2020-08-24 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20200824_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='notice',
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='接受者')),
            ],
        ),
    ]
